affine.c: affine.h
affine.c: point.h
affine.c: xfrm.h
affine.h: space.h
bbox.c: bbox.h
bbox.h: util.h
bitstring.c: bitstring.h
cli.c: compute.h
color.h: point.h
color.h: space.h
dynamic-setup.c: affine.h
dynamic-setup.c: bbox.h
dynamic-setup.c: color.h
dynamic-setup.c: dynamic-setup.h
dynamic-setup.c: point.h
dynamic-setup.c: serial.h
dynamic-setup.c: simplex.h
dynamic-setup.c: slist.h
dynamic-setup.c: wavefront-file.h
dynamic-setup.c: xfrm.h
dynamic-setup.h: raytrace.h
dynamic-setup.h: space.h
dynamic-setup.h: track.h
file2array.c: util.h
gui.c: gui-indep.c
gui.c: gui-opengl.c
gui.c: lightcut.h
gui-indep.c: gui-indep.h
gui-indep.h: dynamic-setup.h
gui-indep.h: motion.h
gui-indep.h: pnm-image.h
gui-indep.h: point.h
gui-indep.h: serial.h
gui-indep.h: testcase.h
gui-indep.h: xfrm.h
imgdiff.c: color.h
imgdiff.c: pnm-image.h
imgdiff.c: space.h
imgdiff.c: util.h
kdtree.c: kdtree.h
kdtree.c: order.h
lightcut.c: lightcut.h
lightcut.h: gmrand.h
material.c: color.h
material.c: material.h
material.c: point.h
material.c: pnm-image.h
material.c: xfrm.h
material.h: space.h
pack.c: pack.h
point.h: op.h
raytrace.c: affine.h
raytrace.c: bbox.h
raytrace.c: bitstring.h
raytrace.c: color.h
raytrace.c: lightcut.h
raytrace.c: order.h
raytrace.c: point.h
raytrace.c: simplex.h
raytrace.c: space-junk.h
raytrace.c: xfrm.h
raytrace.h: kdtree.h
raytrace.h: kptree.h
raytrace.h: scene.h
raytrace.h: space.h
scene.h: space.h
scene.h: material.h
testcase.c: testcase.h
util.c: util.h
verif/main.c: affine.h
verif/main.c: bbox.h
verif/main.c: bitstring.h
verif/main.c: gmrand.h
verif/main.c: kdtree.h
verif/main.c: kptree.h
verif/main.c: order.h
verif/main.c: point.h
verif/main.c: scene.h
verif/main.c: serial.h
verif/main.c: slist.h
verif/main.c: util.h
verif/main.c: xfrm.h
